spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

#        - id: order-service
#          uri: lb://vtidn2505-order-service
#          predicates:
#            - Path=/api/v1/order/**
#
#        - id: product-service
#          uri: lb://vtidtn2505-product-service
#          predicates:
#            - Path=/api/v1/product/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/vti-dtn-2506
          jwt-set-uri: http://localhost:8080/realms/vti-dtn-2506/protocol/openid-connect/certs

    permissions:
      - path: /api/auth/**
        permit-all: true

      - path: /api/v1/order/**
        roles:
          - ROLE_USER

      - path: /api/v1/products/**
        roles:
          - ROLE_USER

server:
  port: 8282

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
#    root: DEBUG
    org.springframework.cloud.gateway: TRACE